# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 00:22
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='testpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
