# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180106_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorexpresssnippet',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
