# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_visitorexpresssnippet_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorexpresssnippet',
            old_name='intro',
            new_name='body',
        ),
    ]
