# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 19:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_carouselitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='home.HomePage'),
        ),
    ]
