# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180109_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='page',
        ),
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
