# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180109_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VEItem',
            new_name='CarouselItem',
        ),
    ]
