# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 22:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180109_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ve_links', to='home.VisitorExpressSnippet'),
        ),
    ]
