# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 22:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180109_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='about_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_links', to='home.AboutSnippet'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='visitor_express_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_links', to='home.VisitorExpressSnippet'),
        ),
    ]
