# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 23:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180109_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='click2park_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_links', to='home.Click2ParkSnippet'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='journey2share_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_links', to='home.Journey2ShareSnippet'),
        ),
    ]
