# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0026_visitorexpressitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click2ParkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='click2park_items', to='home.Click2ParkSnippet')),
            ],
        ),
        migrations.CreateModel(
            name='Journey2ShareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey2share_items', to='home.Journey2ShareSnippet')),
            ],
        ),
        migrations.RemoveField(
            model_name='veitem2',
            name='image',
        ),
        migrations.RemoveField(
            model_name='veitem2',
            name='page',
        ),
        migrations.RemoveField(
            model_name='veitem3',
            name='image',
        ),
        migrations.RemoveField(
            model_name='veitem3',
            name='page',
        ),
        migrations.DeleteModel(
            name='VEItem2',
        ),
        migrations.DeleteModel(
            name='VEItem3',
        ),
    ]
