# Generated by Django 2.1.4 on 2018-12-29 01:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0029_auto_20181011_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.AboutSnippet')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_snippettag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.SnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
