# Generated by Django 2.1.4 on 2018-12-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20181229_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsnippet',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
