# Generated by Django 2.1.4 on 2018-12-29 02:00

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0031_auto_20181229_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='click2parksnippet',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='click2parksnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.SnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='journey2sharesnippet',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey2sharesnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.SnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='visitorexpresssnippet',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorexpresssnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.SnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
