# Generated by Django 2.1.4 on 2018-12-29 02:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0032_auto_20181229_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSnippetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudySnippetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Click2ParkSnippetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journey2ShareSnippetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorExpressSnippetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='snippettag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='snippettag',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='casestudysnippet',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='click2parksnippet',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='journey2sharesnippet',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='visitorexpresssnippet',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='casestudysnippet',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.AboutSnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='click2parksnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.Click2ParkSnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='journey2sharesnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.Journey2ShareSnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='visitorexpresssnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.VisitorExpressSnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='SnippetTag',
        ),
        migrations.AddField(
            model_name='visitorexpresssnippettag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.VisitorExpressSnippet'),
        ),
        migrations.AddField(
            model_name='visitorexpresssnippettag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_visitorexpresssnippettag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='journey2sharesnippettag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.Journey2ShareSnippet'),
        ),
        migrations.AddField(
            model_name='journey2sharesnippettag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_journey2sharesnippettag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='click2parksnippettag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.Click2ParkSnippet'),
        ),
        migrations.AddField(
            model_name='click2parksnippettag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_click2parksnippettag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='casestudysnippettag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.CaseStudySnippet'),
        ),
        migrations.AddField(
            model_name='casestudysnippettag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_casestudysnippettag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='aboutsnippettag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.AboutSnippet'),
        ),
        migrations.AddField(
            model_name='aboutsnippettag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_aboutsnippettag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='casestudysnippet',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.CaseStudySnippetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
