# Generated by Django 2.1.4 on 2018-12-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_casestudysnippet_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsnippet',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='casestudysnippet',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='click2parksnippet',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='journey2sharesnippet',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='visitorexpresssnippet',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='click2parksnippet',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey2sharesnippet',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorexpresssnippet',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
