# Generated by Django 2.1.4 on 2018-12-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20181230_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='casestudyitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='casestudyitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='click2parkitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='click2parkitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='journey2shareitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='journey2shareitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='visitorexpressitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='visitorexpressitem',
            name='page',
        ),
        migrations.DeleteModel(
            name='AboutItem',
        ),
        migrations.DeleteModel(
            name='CaseStudyItem',
        ),
        migrations.DeleteModel(
            name='Click2ParkItem',
        ),
        migrations.DeleteModel(
            name='Journey2ShareItem',
        ),
        migrations.DeleteModel(
            name='VisitorExpressItem',
        ),
    ]
