# Generated by Django 2.1.4 on 2019-01-04 11:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20181230_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_support',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
